name: Publish, Release and Docs

on:
  workflow_dispatch:
    inputs:
      version_override:
        description: 'Version override (format is "a.b.c", or use "auto" to extract version from package.json)'
        default: 'auto'
      is_draft:
        description: 'Is this release draft? (true/false)'
        default: 'false'
      is_prerelease:
        description: 'Is this prerelease? (true/false)'
        default: 'false'
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions: write-all
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3

      - name: Setup .npmrc file to publish to npm
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install modules
        run: npm install

      - name: Build
        run: npm run build

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  release:
    runs-on: ubuntu-latest
    needs: publish
    permissions: write-all
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Read version from package.json
        uses: amochkin/action-json@v1
        id: read_version
        with:
          property: version
          override_with: ${{ github.event.inputs.version_override }}
          use_override: ${{ github.event.inputs.version_override != 'auto' }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ steps.read_version.outputs.value }}
          draft: ${{ github.event.inputs.is_draft }}
          prerelease: ${{ github.event.inputs.is_prerelease }}
          tag_name: ${{ steps.read_version.outputs.value }}

  docs:
    runs-on: ubuntu-latest
    needs: release
    permissions: write-all
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install modules
        run: npm install

      - name: Build
        run: npm run docs:build

      - name: Patch
        run: npm run docs:patch

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 662b9e7e1ff6240e1340da82b4c50b06
          projectName: ferramenta
          directory: docs
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
