name: Release & Publish

on:
  workflow_dispatch:
    inputs:
      version_override:
        description: 'Version override (format is "a.b.c", or use "auto" to extract version from package.json)'
        default: 'auto'
      is_draft:
        description: 'Is this release draft? (true/false)'
        default: 'false'
      is_prerelease:
        description: 'Is this prerelease? (true/false)'
        default: 'false'
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions: write-all
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - name: Setup .npmrc file to publish to npm
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install modules
        run: npm install
      - name: Build
        run: npm run build
      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  release:
    runs-on: ubuntu-latest
    needs: publish
    permissions: write-all
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Extract version from package.json
        uses: amochkin/gha-json-value@v1-rc6
        id: extract-version
        with:
          property: version
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.version_override == 'auto' && github.steps.extract-version.outputs.value || github.event.inputs.version_override }}
          release_name: v${{ github.event.inputs.version_override == 'auto' && github.steps.extract-version.outputs.value || github.event.inputs.version_override }}
          draft: ${{ github.event.inputs.is_draft }}
          prerelease: ${{ github.event.inputs.is_prerelease }}

  docs:
    runs-on: ubuntu-latest
    needs: release
    permissions: write-all
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install modules
        run: npm install
      - name: Build
        run: npm run docs:build
      - name: Patch
        run: npm run docs:patch
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 662b9e7e1ff6240e1340da82b4c50b06
          projectName: ferramenta
          directory: docs
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
