name: Release

on:
  workflow_dispatch:
    inputs:
      version_override:
        description: 'Version override (format is "a.b.c", or use "auto" to extract version from package.json)'
        default: 'auto'
      is_draft:
        description: 'Is this release draft? (true/false)'
        default: 'false'
      is_prerelease:
        description: 'Is this prerelease? (true/false)'
        default: 'false'
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    needs: publish
    permissions: write-all
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Read version from package.json
        uses: amochkin/action-json@v1
        id: read_version
        with:
          property: version
          override_with: ${{ github.event.inputs.version_override }}
          use_override: ${{ github.event.inputs.version_override != 'auto' }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.read_version.outputs.value }}
          release_name: v${{ steps.read_version.outputs.value }}
          draft: ${{ github.event.inputs.is_draft }}
          prerelease: ${{ github.event.inputs.is_prerelease }}
